POST http://localhost:19091/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoidGVzdElkIiwicm9sZSI6IlJPTEVfVVNFUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTcyMzI2NjU3NSwiZXhwIjoxNzIzMjcwMTc1fQ.0EFJ-ywv-v7YWl0Vri0ZTiqcenSw9xb4UgghDC-G5Bq3JRbMKj_NEBabh1F53qwQNKLFDcLaedssv5tU6hMR8g

{
  "name": "상품이름",
  "supply_price": 10000
}

###
