POST http://localhost:19093/products
Content-Type: application/json

{
  "name": "",
  "supply_price": 3000
}

###

POST http://localhost:19093/products
Content-Type: application/json

{
  "name": "ccc"
}

###


POST http://localhost:19093/products
Content-Type: application/json

{
  "name": "ccc",
  "supply_price": -100
}

###
