POST http://localhost:19092/order
Content-Type: application/json

{
  "name": "abc",
  "productIds": [
    1,
    2,
    3
  ]
}

###

POST http://localhost:19092/order
Content-Type: application/json

{
  "name": "abc"
}

###
